export const categories = [
    'Actualités nationales',
    'Actualités internationales',
    'Politique',
    'Économie',
    'Sport',
    'Culture',
    'Technologie',
    'Santé',
    'Sciences',
    'Environnement',
    'Faits divers',
    'Éducation',
    'Opinions',
    'Divertissement',
    'Mode',
    'Cuisine',
    'Voyages',
    'Religion',
    'Météo',
  ];